name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 13306
        container port: 3306
        mysql version: '5.7'
        mysql database: books
        mysql root password: ''
        mysql user: 'root'
        mysql password: 'root'
        
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        host port: 5432
        container port: 5432
        postgresql user: 'root'
        postgresql password: 'pgsql'

    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile coverage.out ./...
