name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
#       sqlserver:
#         image: mcr.microsoft.com/mssql/server:2019-latest
#         env:
#           MSSQL_IP_ADDRESS: 0.0.0.0
#           MSSQL_SA_PASSWORD: 'mssql'
#           ACCEPT_EULA: Y
#         ports:
#           - 1401:1433

    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql user: 'root'
        postgresql password: 'pgsql'
        
    - name: Setup SQL Server
      uses: 280780363/sqlserver-action@v1.0
      with:
        accept eula: Y
        sa password: "mssql"

    - name: Verify MySQL connection
      run: |
        sudo apt-get install -y mariadb-client
        mariadb --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -e "SHOW DATABASES"
        
    - name: Verify SQL Server connection
      run: |
        sqlcmd -S tcp:127.0.0.1,1433 -U SA -P "mssql"

    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -coverprofile coverage.out ./...
